/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import admin.admindash;
import config.dbconnector;
import java.awt.event.KeyEvent;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import user.userdash;


/**
 *
 * @author entac
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    
    public static dbconnector connector = new dbconnector();
    
    public login() {
        initComponents();
    }
        
    public static boolean loginAcc(String user, String pass){
        
        try{
            String sql = "SELECT * FROM admin  WHERE user = '" + user + "' AND pass = '" + pass +"'";
            ResultSet resultSet = connector.getData(sql);
            return resultSet.next();
        }catch (SQLException ex) {
            return false;
        }

    }
    
     public static boolean stat(String user){
        
        try{
            String sql = "SELECT * FROM admin  WHERE user = '"+user+"' AND status = 'Active'";
            ResultSet resultSet = connector.getData(sql);
            return resultSet.next();
        }catch (SQLException ex) {
            return false;
        }

    }
     
     public static boolean type(String user){
        
        try{
            String sql = "SELECT * FROM admin  WHERE user = '"+user+"' AND type = 'Admin' ";
            ResultSet resultSet = connector.getData(sql);
            return resultSet.next();
        }catch (SQLException ex) {
            return false;
        }

    }
     
     
    
     public static String passHash(String pass){
         try{
             MessageDigest md = MessageDigest.getInstance("SHA");
             md.update(pass.getBytes());
             byte[] rb = md.digest();
             StringBuilder sb = new StringBuilder();
             
             for(byte b: rb){
                 sb.append(String.format("%02x", b));
             }
             
             return sb.toString();
             
         }catch(NoSuchAlgorithmException ex){
         
         }
         return null;
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        signup = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        cmdlog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Username");
        sel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));
        sel.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 160, 30));

        signup.setText("Sign Up");
        signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupMouseClicked(evt);
            }
        });
        sel.add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, 20));

        jLabel3.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel3.setText("Log In");
        sel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 70, -1));

        txtpass.setToolTipText("");
        txtpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpassKeyPressed(evt);
            }
        });
        sel.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 160, 30));

        jLabel4.setText("Password");
        sel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        cmdlog.setText("Log In");
        cmdlog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdlogMouseClicked(evt);
            }
        });
        sel.add(cmdlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 170, -1));

        getContentPane().add(sel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 421, 245));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdlogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdlogMouseClicked
         if(!loginAcc(txtuser.getText(),txtpass.getText())){
             JOptionPane.showMessageDialog(null,"Invalid");
             txtuser.setText("");
             txtpass.setText("");
         
         }else{
            if(stat(txtuser.getText())){
                if(type(txtuser.getText())){
                admindash open = new admindash();
             
               try {
                     String sq = "SELECT * FROM admin WHERE user = '" +txtuser.getText()+ "'";
                     ResultSet res = connector.getData(sq);
                     if(res.next()){
                         String n = res.getString("Name");
                         String l = res.getString("Last");
                         String i = res.getString("id");
                          open.name.setText("<html><body><center>"+l +","+ n +"</center></body></html>");
                          open.lblid.setText(i);
                         
                     }
                     
                 } catch (SQLException ex) {
                     Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                 }
             
            JOptionPane.showMessageDialog(null,"Welcome Admin");
            open.setVisible(true);
            this.dispose();
              }else{
                    userdash us = new userdash();
                    JOptionPane.showMessageDialog(null,"Welcome");
                    us.setVisible(true);
                    this.dispose();
                }
               
            }else{
                JOptionPane.showMessageDialog(null, "Your account is pending. Please wait for activation.");
            }
        }
    }//GEN-LAST:event_cmdlogMouseClicked

    private void txtpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyPressed
      String password = passHash(txtpass.getText());
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
          if(!loginAcc(txtuser.getText(),password)){
             JOptionPane.showMessageDialog(null,"Invalid");
             txtuser.setText("");
             txtpass.setText("");
         }else{
            if(stat(txtuser.getText())){
                if(type(txtuser.getText())){
                admindash open = new admindash();
             
              
               try {
                     String sq = "SELECT * FROM admin WHERE user = '" +txtuser.getText()+ "'";
                     ResultSet res = connector.getData(sq);
                   if(res.next()){
                         String n = res.getString("Name");
                         String l = res.getString("Last");
                         String i = res.getString("id");
                          open.name.setText("<html><body><center>"+l +","+ n +"</center></body></html>");
                          open.lblid.setText(i);
                         
                     }
                     
                 } catch (SQLException ex) {
                     Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                 }
             
            JOptionPane.showMessageDialog(null,"Welcome Admin");
            open.setVisible(true);
            this.dispose();
              }else{
                    userdash us = new userdash();
                    
               try {
                     String sq = "SELECT * FROM admin WHERE user = '" +txtuser.getText()+ "'";
                     ResultSet res = connector.getData(sq);
                     if(res.next()){
                         String n = res.getString("Name");
                         String l = res.getString("Last");
                         String i = res.getString("id");
                         us.name.setText("<html><body><center>"+l +","+ n +"</center></body></html>");
                         us.lblid.setText(i);
                     }
                     
                 } catch (SQLException ex) {
                     Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                 }
             
            JOptionPane.showMessageDialog(null,"Welcome User");
            us.setVisible(true);
            this.dispose();
                }
               
            }else{
                JOptionPane.showMessageDialog(null, "Your account is pending. Please wait for activation.");
            }
              
         }   
      }
    }//GEN-LAST:event_txtpassKeyPressed

    private void signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseClicked
      sign op = new sign();
      op.action = "reg";
      op.reg.setText("Register");
      op.cmdsave.setText("Save");
      op.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_signupMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdlog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel sel;
    private javax.swing.JLabel signup;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
