
package form;

import config.dbconnector;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author entac
 */
public class sign extends javax.swing.JFrame {

    /**
     * Creates new form sign
     */
    
    dbconnector db = new dbconnector();
    
    public sign() {
        initComponents();
    }
    public static String un, email, id;
    
    public boolean duplicate(){
        try{
            String quer = "SELECT * FROM admin WHERE user ='"+txtuser.getText()+"' OR email = '"+txtemail.getText()+"' "
                    + "OR id = '"+txtid.getText()+"'";
            ResultSet res = db.getData(quer);
            
            if(res.next()){
                id = res.getString("id");
                 if(id.equals(txtid.getText())){
                  JOptionPane.showMessageDialog(null,"ID Aready Used"); 
                  txtid.setText("");
                }
                email = res.getString("email");
                if(email.equals(txtemail.getText())){
                  JOptionPane.showMessageDialog(null,"Email Aready Used"); 
                  txtemail.setText("");
                }
                un = res.getString("user");
                if(un.equals(txtuser.getText())){
                  JOptionPane.showMessageDialog(null,"Username Aready Used");  
                  txtuser.setText("");
                }
                return true;
            }else{
                return false;
            }
        }catch(SQLException ex){
            System.out.println("ERROR"+ex.getMessage());
            return false;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtlast = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        cmdcancel = new javax.swing.JButton();
        cmdsave = new javax.swing.JButton();
        txtpass = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel1.setText("Register");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 40));

        jLabel2.setText("ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 30));
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 150, 30));
        jPanel1.add(txtlast, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 150, 30));

        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 30));
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 150, 30));

        jLabel4.setText("Email");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 30));
        jPanel1.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 150, 30));

        jLabel5.setText("Username");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 30));

        jLabel6.setText("User Type");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 30));

        jLabel7.setText("Password");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 30));

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));
        jPanel1.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 150, 30));

        cmdcancel.setText("Cancel");
        cmdcancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdcancelMouseClicked(evt);
            }
        });
        jPanel1.add(cmdcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 80, 30));

        cmdsave.setText("Save");
        cmdsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdsaveMouseClicked(evt);
            }
        });
        jPanel1.add(cmdsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 80, 30));
        jPanel1.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 150, 30));

        jLabel8.setText("Name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(382, 476));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdsaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdsaveMouseClicked
        if(txtid.getText().isEmpty() || txtname.getText().isEmpty() || txtlast.getText().isEmpty() || txtemail.getText().isEmpty() 
                || txtuser.getText().isEmpty() || txtpass.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null,"All Fields Are Required");
        }else if(txtpass.getText().length() < 8){
            JOptionPane.showMessageDialog(null,"Password must be 8 or more Characters");
            
        }else if(duplicate()){
            System.out.println("Duplicated");
        }else{
            if(db.insertData("INSERT INTO admin (id, Name, Last, email, type, user, pass, status) "
                    + "VALUES ('"+txtid.getText()+"','"+txtname.getText()+"','"+txtlast.getText()+"','"+txtemail.getText()+"','"+type.getSelectedItem()+"',"
                            + "'"+txtuser.getText()+"','"+txtpass.getText()+"','Pending')"))
            {
                JOptionPane.showMessageDialog(null,"Saved");
                login log = new login();
                log.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null,"Error");
            }
            
        }
    }//GEN-LAST:event_cmdsaveMouseClicked

    private void cmdcancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdcancelMouseClicked
      int l = JOptionPane.showConfirmDialog(null,"Are You Sure you Want to Cancel?","Select" , JOptionPane.YES_NO_OPTION);
      if(l == 0){
          this.dispose();
      }
    }//GEN-LAST:event_cmdcancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sign().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdcancel;
    private javax.swing.JButton cmdsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtlast;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
