/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.dbconnector;
import form.login;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author entac
 */
public class users extends javax.swing.JFrame {

    /**
     * Creates new form admindash
     */
    dbconnector db = new dbconnector();
    public users() {
        initComponents();
        tb();
    }
    
    Color nav = new Color(204,0,0);
     Color ex = new Color(102,0,0);

     
     public void tb(){
         try{
             ResultSet res = db.getData("SELECT id,Name,Last,email,type,status FROM admin ORDER BY Last");
             userlist.setModel(DbUtils.resultSetToTableModel(res));
             res.close();
         }catch(SQLException x){
             System.out.println("Error" +x.getMessage());
             
         }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        us = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userlist = new javax.swing.JTable();
        statup = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel1.setText("User Profiles");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/logout.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 70));

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        us.setBackground(new java.awt.Color(102, 0, 0));
        us.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usMouseExited(evt);
            }
        });
        us.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("  USERS");
        us.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 70, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/users.png"))); // NOI18N
        us.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel2.add(us, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 110));

        userlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(userlist);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 680, 360));

        statup.setBackground(new java.awt.Color(102, 0, 0));
        statup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                statupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                statupMouseExited(evt);
            }
        });
        statup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Status Update");
        statup.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 5, -1, -1));

        jPanel2.add(statup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 140, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 840, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
       new admindash().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void usMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usMouseEntered
       us.setBackground(nav);
    }//GEN-LAST:event_usMouseEntered

    private void usMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usMouseExited
      us.setBackground(ex);
    }//GEN-LAST:event_usMouseExited

    private void statupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statupMouseEntered
        statup.setBackground(nav);
    }//GEN-LAST:event_statupMouseEntered

    private void statupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statupMouseExited
        statup.setBackground(ex);
    }//GEN-LAST:event_statupMouseExited

    private void statupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statupMouseClicked
        int row = userlist.getSelectedRow();
        
        if(row < 0){
            JOptionPane.showMessageDialog(null,"Select User");
        }else{
            TableModel tbl = userlist.getModel();
            
            statup op = new statup();
            op.idno.setText(tbl.getValueAt(row, 0).toString());
            op.ustype.setSelectedItem(tbl.getValueAt(row, 4).toString());
            op.stats.setSelectedItem(tbl.getValueAt(row, 5).toString());
            
            op.setVisible(true);
            JFrame mainFrame = (JFrame)SwingUtilities.getWindowAncestor(this);
            this.dispose();
        }
        
        
    }//GEN-LAST:event_statupMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new users().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel statup;
    private javax.swing.JPanel us;
    private javax.swing.JTable userlist;
    // End of variables declaration//GEN-END:variables
}
